version: '3.1'
services:
    mysql:
        image: 'mariadb:10.6'
        environment:
          - MYSQL_ROOT_PASSWORD=xxxxxx
          - MYSQL_DATABASE=blog
        ports:
          - "3306:3306"
        container_name: 'mysql-blog'
        volumes:
          - './mysql_data:/var/lib/mysql'
        restart: always